version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ../src/back/.env
    depends_on:
      - mongodb

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: